### ISSUE TITLE
Find users in repository information

### ISSUE THREAD

**Issue by andrewda** [coala/gci-leaders#100]
We should check the `watchers`, `stargazers` and `forks` for all repositories owned by an organization to see if the user appears there. Luckily, GraphQL makes this _super_ easy.

```GraphQL
{
  organization(login: "coala") {
    repositories(first: 100) {
      nodes {
        watchers(first: 100) {
          nodes {
            login
            name
          }
        }
        stargazers(last: 100) {
          nodes {
            login
            name
          }
        }
        forks(first: 100) {
          nodes {
            owner {
              login
            }
          }
        }
      }
    }
  }
}
```

Check all those `login`s and `name`s against the GCI `display_names` in the organization to find matches. I did a manual check and this will find _at least_ another 5-10 matches, including 3 more from coala.

**Comment by andrewda** [comment]
Bonus points for using pagination to get more than just the first page:

```graphql
{
  organization(login: "coala") {
    repositories(first: 100) {
      nodes {
        name
        watchers(first: 100) {
          nodes {
            login
            name
          }
          pageInfo {
            endCursor
            hasNextPage
          }
        }
        stargazers(first: 100) {
          nodes {
            login
            name
          }
          pageInfo {
            endCursor
            hasNextPage
          }
        }
      }
    }
  }
}
```

**Comment by jayvdb** [comment]
Note that for this to avoid false positives, it should only look for watchers, stargazers and forks that occurred after the start of GCI.  These orgs have too many historical watchers, stargazers and forks , so the chance of two people with the same name is quite high.

**Comment by andrewda** [comment]
@jayvdb GitHub does not return the time of stars/watches, but that can be done for forks at least.

**Comment by andrewda** [comment]
Revising what I said earlier: pagination isn't going to be possible using this method because we'd have to be paginating for the watchers, stargazers and forks in _each_ of the 100 repository. Even if we could keep track of all 300 cursors, I don't think there's a way in GraphQL to use them per repository.

Anyways, here's a list of users found (some already existing prior to this, but many new):

| GCI Display Name | GitHub Username |
| :---- | :---- |
| Akshit Dewan | @akshitdewan |
| Sachin Rammoorthy | @sachinrammoorthy |
| Saba Khukhunashvili | @sabakhukhunashvili |
| Sidhya Tikku | @sidhyatikku |
| Utkarsh Verma | @utkarshverma |
| phyxkal | @phyxkal |
| Gautam Jajoo | @gautamjajoo |
| Raghav Puri | @raghavpuri |
| Suraj Datta | @surajdatta |
| eviltak | @eviltak |
| kipply | @kipply |
| luphieanza | @luphieanza |
| Akash Bhave | @akashbhave |
| Chirag Gupta | @luckyman20 |
| Yibin Long | @yibinlong |
| Andrew Dassonville | @andrewda |
| biscuitsnake | @biscuitsnake |
| Nalin Bhardwaj | @nalinbhardwaj |
| Hartama | @haruute0 |
| synicalsyntax | @synicalsyntax |
| Erika Tan | @erikatan |
| Abhijeet Manohar | @abhijeetmanohar |
| Vatsal Kulshreshtha | @vatsalkulshreshtha |
| Jyothsna Ashok | @jyothsnaashok |
| Sanskar Jindal | @sanskarjindal |
| Abishek V Ashok | @abishekvashok |
| Samyak Jain | @sj29-innovate |
| Yash Kumar Verma | @yashkumarverma |

If you came to this issue from a ping and are not a part of Google Code-In, please let me know 😄

**Comment by SachinRammoorthy** [comment]
What is this?

**Comment by andrewda** [comment]
👋  Hi @SachinRammoorthy! Sorry, I should have been more clear about that above. This is [a website](https://gci-leaders.netlify.com) for seeing the leaders of all Google Code-In organizations. I see you're a GCI student so you can safely ignore this ping, but definitely check out the site if you're interested!

**Comment by abishekvashok** [comment]
Can I know in what criteria have you arranged the names. To note: I didn't participate with coala in gci this year.

**Comment by andrewda** [comment]
Those names aren't arranged in any order, really. They're all the names of people from the GCI leaderboards (for all organizations, not just coala) that we detected to be linked with a GitHub account. They will be used on https://gci-leaders.netlify.com to make it easy to see the GitHub accounts of specific students.

**Comment by m-sameer** [comment]
@andrewda I have a question and a request(well, kinda):
Question: Can I know how many tasks someone did from an API?


Request: I am Sameer, the one with a leader name on Systers.So it'll be great if you linked my name to my Github account. So here's my Github profi.....wait, you got it.

**Comment by andrewda** [comment]
There isn't any public API to request the number of tasks completed by each person. Google wants the students to focus on doing quality work instead of doing a lot of tasks, so it makes sense not to make that information public.

We use several different searches to try and find the GitHub accounts for each user (but nothing can be linked manually, at least at the moment). It might be tough to automatically link your GitHub account because your GitHub name ("Mohammad Sameer") differs from your GCI display name ("Sameer"). Right now, we're depending on those too being identical.

**Comment by m-sameer** [comment]
_Negative feedback to both_. 

Thanks anyway. :-)
