### ISSUE TITLE
Add .coafile

### ISSUE THREAD

**Issue by blazeu** [coala/gci-leaders#11]
It should check for the file types already in the repository.
Exclude `package*.json` file and `out` folder.

Ideally we should use prettier.io to format, because initially I used that.
But [PrettierBear](https://github.com/coala/coala-bears/issues/2130) doesn't exists yet.

So, use ESLintBear and https://github.com/prettier/eslint-plugin-prettier instead.

The settings should be:
- no semicolon
- es5 trailing commas
- single quote

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by blazeu** [comment]
Ideally we should use prettier.io to format, but PrettierBear doesn't exists yet.

So, use ESLintBear and https://github.com/prettier/eslint-plugin-prettier instead.
