### ISSUE TITLE
Use GraphQL API

### ISSUE THREAD

**Issue by andrewda** [coala/gci-leaders#111]
We should use GitHub's GraphQL API instead of the the REST API. This will let us get a lot more data in many fewer requests.

You should preferably already have some GraphQL experience in order to properly make use of everything GraphQL has to offer, such as pagination and query variables.

Check out https://www.npmjs.com/package/graphql-client for making requests.

**Comment by li-boxuan** [comment]
@andrewda @jayvdb One problem with `searchGitHubOrgs` function: via REST API, GitHub would return a `score` to represent matching degree. 

[scrape.js#L287-L289](https://github.com/coala/gci-leaders/blob/master/lib/scrape.js#L287-L289) uses `score` attribute to see if it reaches threshold.

However, as far as I am concerned, GraphQL API would not return `score` or anything like that.
```graphql
query($name: String!) {
    search(type:USER, query:$name, first:1) {
        nodes {
            ...on Organization {
                login
            }
        }
    }
}
```
I would like to work on this issue.

**Comment by li-boxuan** [comment]
Another thing is, the function `findGitHubUserInOrg` on [scrape.js#L505](https://github.com/coala/gci-leaders/blob/master/lib/scrape.js#L505) uses `${GH_ORG_BASE}/${org}/people?query=${user}` and regex to check if a user is in an org. This is ad-hoc but doesn't need any API quota. REST API and GraphQL API can do this check but of course, would use API quota. Is this design by intention?

**Comment by jayvdb** [comment]
Regarding `findGitHubUserInOrg`, the choice of what to use is made based on how to do as much validation without hitting the limit.
