### ISSUE TITLE
Remove duplicate history actions

### ISSUE THREAD

**Issue by andrewda** [coala/gci-leaders#116]
https://github.com/coala/gci-leaders/blob/57bfbd8c0491e9c7033c8bc720dbc5f40cb81c68/lib/scrape.js#L105-L111

`created_issues` is checked twice, meaning unnecessary API calls

**Comment by sthkindacrazy** [comment]
I have found this also and deleted one. 
made pr https://github.com/coala/gci-leaders/pull/127

**Comment by sthkindacrazy** [comment]
Following the convention for commit message, I made a new pr https://github.com/coala/gci-leaders/pull/133

**Comment by blazeu** [comment]
@sthkindacrazy umm this is supposed to be a Google code-in task

**Comment by Ananthavijay** [comment]
can I be assigned for this issue?

**Comment by Ananthavijay** [comment]
This PR : https://github.com/coala/gci-leaders/pull/145 closes this

**Comment by Ananthavijay** [comment]
This PR : https://github.com/coala/gci-leaders/pull/146 fixes the issue
