### ISSUE TITLE
Add year variable, set to 2018

### ISSUE THREAD

**Issue by jayvdb** [coala/gci-leaders#153]
https://codein.withgoogle.com/api/program/2017/organization/?status=2 is 404.

https://codein.withgoogle.com/api/program/2018/organization/?status=2 is at least valid json

Ideally the year variable is set to the previous or current year, *depending* on which JSON of the above is the best.

i.e. on Jan 1 2019, the website still needs to be using 2018 , and should keep using 2018 until the 2019 org data is more valid.

**Comment by jayvdb** [comment]
This could be low difficulty, if a quick fix is done to get the build working, or medium difficulty to do it well.

**Comment by utkarsh2102** [comment]
Hi @jayvdb,
Could I be assigned this issue?
I'm at PyCon India's DevSprint.

**Comment by nickdex** [comment]
Why aren't you guys using this url? - [Google CodeIn Api](https://codein.withgoogle.com/api/program/current/)
It gives same JSON response as https://codein.withgoogle.com/api/program/2018/
I'm assuming using current instead of a year number will always give you valid json without additional code

**Comment by utkarsh2102** [comment]
Yeah, this makes sense.

**Comment by jayvdb** [comment]
@nickdex , that is already being loaded in `fetchDates()` of `lib/scrape.js`.  This tool actually handles all previous years as well as the current year, including years without json.  I believe @utkarsh2102 is close to having a new version of the PR ready, and it would be lovely if you helped with code review ;-)

**Comment by nickdex** [comment]
@jayvdb Ah I see, my bad. I only gave it a cursory glance and sure, happy to help.
