### ISSUE TITLE
Display the number of tasks completed for each org

### ISSUE THREAD

**Issue by jayvdb** [coala/gci-leaders#16]
#4 only sorted.  The number of tasks completed should be shown.

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the label prediction failed because there are not enough labels. Three labels must have been set on at least three issues each.

The contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by jayvdb** [comment]
Also the italics at the top still says sorted alphabetically.  Also fix that.

**Comment by blazeu** [comment]
The italics at the top is meant for the participants not the organization.

**Comment by jayvdb** [comment]
@blazeu , that should be clarified ;-)
