### ISSUE TITLE
scrape.js: Check whether property `repositories` exist

### ISSUE THREAD

**Issue by li-boxuan** [coala/gci-leaders#160]
the netlify build is failing in node ./lib/scrape.js with 4:49:43 AM: (node:1600) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'repositories' of null

See https://app.netlify.com/sites/gci-leaders/deploys/5bd23a31fdd72a47225b2ad3

**Comment by jayvdb** [comment]
Why does it fail ?

What was the cause?

Is the data structure different?

**Comment by li-boxuan** [comment]
It fails because in https://codein.withgoogle.com/api/program/2018/organization/?status=2, AOSSIE org has IRC_CHANNEL https://gitter.im/GCI-AOSSIE, thus `scrape.js` infers they have GitHub org called `GCI-AOSSIE`, which is not true. I'll fix it in a better way later today.
