### ISSUE TITLE
Add explicit instruction to install npm v5.8.0 in Readme.md

### ISSUE THREAD

**Issue by fireballpoint1** [coala/gci-leaders#167]
The deafult installation versin of npm via `apt install npm` is v3.5.2 but we need v5.8.0 to run this repo. 
Add `sudo npm install -g npm@5.8.0` to the installation instructions

**Comment by jayvdb** [comment]
Ya, nice idea!

**Comment by jayvdb** [comment]
You could also add why -- npm 5.8.0 is the latest release of npm which properly supports optional dependencies -- so it wont download extra bits that are not needed, which can help for people with high cost mobile connections.
