### ISSUE TITLE
Create a README.md

### ISSUE THREAD

**Issue by jayvdb** [coala/gci-leaders#2]
The new README should explain the 

- basic objects of the projects, and
- the technologies used,
- how developers can build it

**Comment by rak-shit** [comment]
I am a newbie here and want to work on this! Please assign me the issue.

**Comment by Naba7** [comment]
@palash25  cn u assign this issue to me? m a newbie

**Comment by dnabanita7** [comment]
@Makman2 @jayvdb assign me this issue ..i am newbie here ... but i have good experience

**Comment by palash25** [comment]
I guess the original PR has been abandoned so @Naba7 can be assigned to it.

**Comment by jayvdb** [comment]
@palash25 , you are right, but this repo is broken atm, so any issues here are going to be a hassle for newcomers, or at least not very desirable as they wont see a build working.

I've manually fixed and merged the abandoned PR, considering it was a GCI participant, so we can get this file started.
