### ISSUE TITLE
Add "built by coala"

### ISSUE THREAD

**Issue by jayvdb** [coala/gci-leaders#22]
This website should mention that it has been built by the coala team.

This is a design task; do just add "built by coala".

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the label prediction failed because there are not enough labels. Three labels must have been set on at least three issues each.

The contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by paavininanda** [comment]
Hey @jayvdb. Do we need to include any image or logo with this? Or just a line at the end of the HTML page would do?

**Comment by blazeu** [comment]
Just add text with a link to coala.

But more importantly, are you on Google Code-in?

**Comment by paavininanda** [comment]
@blazeu Can these issues be taken up by GCI students only? I am a GCI mentor.

**Comment by blazeu** [comment]
issues labelled initiatives/gci are for GCI students only ;)

**Comment by parthNanda** [comment]
I want to work on this task. Please assign this to me.
