### ISSUE TITLE
Add fork me ribbon

### ISSUE THREAD

**Issue by jayvdb** [coala/gci-leaders#26]
e.g. https://github.com/blog/273-github-ribbons

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by priyanshsaxena** [comment]
@jayvdb I'd look to work on this. Should the ribbon show up on the main website of [Coala](https://coala.io) ? Is there any specific design-requirement ? Is there some IRC channel (or Gitter or Slack) where I may discuss this ?

**Comment by nemani** [comment]
http://tholman.com/github-corners/

**Comment by priyanshsaxena** [comment]
@jayvdb @nemaniarjun I'd like to take this up. Any pointers on where to place this will be helpful.

**Comment by eeshan9815** [comment]
@jayvdb @nemaniarjun I would like to take up this issue if no one is contributing to it

**Comment by Ananthavijay** [comment]
can i take up this issue??

**Comment by Ananthavijay** [comment]
no i dont want this issue....I already have a newcomer issue..thanks

**Comment by Makman2** [comment]
Unassigning due to inactivity.

**Comment by rohanrk** [comment]
I would like to work on this issue
