### ISSUE TITLE
WIP: Add linting of YAML files to .coafile

### ISSUE THREAD

**Issue by jayvdb** [coala/gci-leaders#28]
.travis.yml , and likely soon .eslintrc

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by blazeu** [comment]
https://github.com/coala/gci-leaders/pull/20

It's there already.
