### ISSUE TITLE
Org heading contains invalid element

### ISSUE THREAD

**Issue by blazeu** [coala/gci-leaders#30]
Task completed and github logo should go outside the `h3` tag.

https://github.com/coala/gci-leaders/blob/ad8d15a6d0e033809b151516258dfe1af1ecd53f/templates/main.html#L24-L33

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.
