### ISSUE TITLE
ESLint should extend from eslint:recommended and eslint-config-prettier rules

### ISSUE THREAD

**Issue by blazeu** [coala/gci-leaders#34]
https://github.com/coala/gci-leaders/pull/20 only adds prettier which focuses on formatting rules.

`eslint:recommended` adds some real linter rules. e.g. unused variable.
[`prettier`](https://github.com/prettier/eslint-config-prettier) rules is used to remove any formatting rules that conflicts with prettier.

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by andrewda** [comment]
My bad for not adding these in #20. Assuming everything passes CI, #37 should add this.
