### ISSUE TITLE
Use NLP to detect nationality statistics 

### ISSUE THREAD

**Issue by jayvdb** [coala/gci-leaders#35]
Use the participants display name to determine nationality.

Discard data which is unsuitable or confidence level is low, but clearly display what percentage of the participants display names were unsuitable or was unusable for the statistics.

wrt unsuitable data, if #32 doesnt land first, skip any display name which contains numerals and doesnt contain an uppercase letter.

To warm you up a bit, see [here](https://www.quora.com/Is-there-a-machine-learning-method-for-detecting-the-nationality-of-a-person-using-their-first-and-last-name)

Come onto the [coala Zulip](https://coala.zulipchat.com/) to discuss how to solve this.

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by andrewda** [comment]
This is really cool! If #8/#32 lands first, we'll also be able to use a user's `location` from GitHub.

**Comment by invisible-defects** [comment]
Sounds really interesting! Have a couple ideas on this, will share them in Zulip soon.

**Comment by jayvdb** [comment]
This task was revised slightly, and wont be done using NLP.
