### ISSUE TITLE
Add i18n

### ISSUE THREAD

**Issue by jayvdb** [coala/gci-leaders#38]
Include at least a few i18n strings, but this task is not about doing translations.

**Comment by jayvdb** [comment]
I think we will want translations to be done on https://hosted.weblate.org/ , but we can set that up after basic functionality is merged.

**Comment by mooncos** [comment]
Ok but can we use a hash table for the strings as of now?

**Comment by jayvdb** [comment]
> Ok but can we use a hash table for the strings as of now?

Yes, we'll incrementally improve.  I am pretty sure weblate knows how to populate jquery.i18n data files
