### ISSUE TITLE
Wrapping problem in `The Mifos Interactive` box

### ISSUE THREAD

**Issue by Mixih** [coala/gci-leaders#47]
Seems to only happen when the screen is over 720p wide (thus probably being css).
Screenshot from firefox 57.0.1 on linux 64bit, 1080 screen width
![screenshot_20171207_210149](https://user-images.githubusercontent.com/5818750/33749234-4218053a-db92-11e7-866b-25379a5f8e7f.png)

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jayvdb.
