### ISSUE TITLE
Design overhaul

### ISSUE THREAD

**Issue by blazeu** [coala/gci-leaders#50]
The current design with multiple columns looks really cramped.

@synicalsyntax Proposed to make a single column instead.

If possible, use and modify the current grid styling.

The new design should look _neat_ and _tidy_ on large (larger than body width), medium (lower than body width) screen and mobile.

And it's allowed to add css for other elements, such as `a` or `li`.

**Comment by jayvdb** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jayvdb.

**Comment by jayvdb** [comment]
Need to assign this to @synicalsyntax after they accept the invite to the coala org.
