### ISSUE TITLE
Add GCI timeline

### ISSUE THREAD

**Issue by blazeu** [coala/gci-leaders#51]
The data can be scraped on build, from
https://codein.withgoogle.com/api/program/current/

**Comment by andrewda** [comment]
Do we know any of the `state` values besides `competition_open`? Or should everything just be done using the provided dates?

**Comment by blazeu** [comment]
I think the value of state are those key with boolean value
e.g. `student_signup_open`, `winners_selection_locked`, `competition_closed`

**Comment by jayvdb** [comment]
Why not just a link to [this](https://developers.google.com/open-source/gci/timeline) GCI website timeline.

I think we should add a countdown or maybe at the moment show percentage of days that have elapsed, which shows new comers that it is still very early and they should still get involved.

**Comment by blazeu** [comment]
Countdown to "Deadline to claim new tasks" looks good.

**Comment by 9r0x** [comment]
I am thinking about something like this: 
<img width="147" alt="screen shot 2017-12-09 at 3 43 28 pm" src="https://user-images.githubusercontent.com/14857092/33793740-2442303c-dcf8-11e7-8420-a131d1b0a6f2.png">
Participants can see the inner dates as a countdown to "Deadline to claim new tasks". while outside circle shows newcomers that it is still very early.

**Comment by blazeu** [comment]
@Grox-Ni I think it's better if the circle and the dates are related ..
