### ISSUE TITLE
Add chat link

### ISSUE THREAD

**Issue by jayvdb** [coala/gci-leaders#53]
Each org lists a URL to their chat system.  Some are direct links, such as https://coala.zulipchat.org or https://gitter.im/scorelab/scorelab or http://systers.io/slack-systers-opensource/ , but others are using that field to store a http page where more information can be found, such as https://github.com/MovingBlocks/Terasology/wiki/Using-IRC .

This task is to add a clickable chat logo beside the github logo.

For this task, find/create a [npm package](https://www.npmjs.com/) which interrogates a URL to return metadata about the chat system.  It should return at least a short name for the type of chat system, such as 'irc', 'gitter', 'zulip', 'slack' and a consistent logo URL for that chat system.

That package can then be used when building this page.

Extra points for extracting direct chat links from the http page some orgs are using instead of direct links into their chat system.

**Comment by andrewda** [comment]
Is there a GCI task for this? Has it already been claimed? (hard to tell without corobo working properly)

I'd like to take this on if it's not already being worked on :+1:
