### ISSUE TITLE
Readable json

### ISSUE THREAD

**Issue by jayvdb** [coala/gci-leaders#57]
Make https://github.com/coala/gci-leaders/blob/gh-pages/data.json readible , and so the history of the file is usable.
Probably also good to emit yaml; which will be more vcs friendly.
Create a separate minified version if required.

**Comment by blazeu** [comment]
~~Probably make a deploy script instead of travis's deploy method also.~~ https://github.com/coala/gci-leaders/pull/59

Since travis will rewrite the history on every deploy.
