### ISSUE TITLE
Broken social link

### ISSUE THREAD

**Issue by andrewda** [coala/gci-leaders#73]
![broken2](https://user-images.githubusercontent.com/10191084/33842961-ebeaabec-de50-11e7-9203-85f1f662773a.png)
![broken1](https://user-images.githubusercontent.com/10191084/33842957-ea53c4bc-de50-11e7-8e22-b1cb268db68d.png)

This probably comes from trying to place a chat link, even though Catrobat doesn't have one.

**Comment by blazeu** [comment]
Probably because mustache check for the `chat` object, empty object is considered true as well.

**Comment by jayvdb** [comment]
If you can give a hint about how to solve this, it becomes a newcomer / beginner task.

**Comment by wisn** [comment]
What solution you guys desire? There are some options. However, the easiest one is to **hide** that element. Just add a simple CSS to hide it.

**Comment by wisn** [comment]
Much easier to add CSS like this I think.

```css
img.chat[src=""] {
  display: none;
}
```

It is now a newcomer task.
